FROM node:6.11.1 as build

WORKDIR /usr/src/app

COPY ./ /usr/src/app

RUN npm i @angular/cli@12.1.2

RUN npm install --force

RUN npm run build

FROM nginx:latest

COPY --from=build /usr/src/app/dist/browser /usr/share/nginx/html

EXPOSE 80